version: '3.7'

services:
  web:
    build: ./services/web
    ports:
      - 5000:5000
    env_file:
      - ./.env
    hostname: web
    privileged: true
    volumes:
      - "./services/web:/usr/src/app/"
    command: ["flask", "run", "--reload"]
    networks:
      mynet:
        aliases:
          - web
  nginx:
    build: ./services/nginx
    ports:
      - 443:8443
    depends_on:
      - web
    hostname: nginx
    networks:
      mynet:
        aliases:
          - nginx
networks:
  mynet:
