version: '3.7'

services:
  web:
    build: ./services/web
    ports:
      - 5000:5000
    env_file:
      - ./.env
    hostname: web
    privileged: true
    volumes:
      - "./services/web:/usr/src/app/"
      - "./dev-backends.yml:/etc/turnpike/backends.yml"
    command: ["flask", "run", "--reload"]
    networks:
      mynet:
        aliases:
          - web
  nginx:
    build: ./services/nginx
    ports:
      - 443:8443
    depends_on:
      - web
    hostname: nginx
    volumes:
      - "./dev-backends.yml:/etc/turnpike/backends.yml"
    networks:
      mynet:
        aliases:
          - nginx
    environment:
      NGINX_PORT: 8443 ssl
      NGINX_SERVER_NAME: nginx
      FLASK_SERVICE_URL: http://web:5000
      NGINX_SSL_CONFIG: |
       ssl_certificate certs/cert.pem;
       ssl_certificate_key certs/key.pem;
  redis:
    image: redis:6
    hostname: redis
    networks:
      mynet:
        aliases:
          - redis
networks:
  mynet:
