apiVersion: v1
kind: Template
labels:
  app: turnpike
  template: turnpike-web
metadata:
  annotations:
    description: Turnpike API gateway - application server
    openshift.io/display-name: Turnpike Flask
  name: turnpike-web
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "redis", "kind": "Service"}]'
    name: web
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      name: web
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: web
    name: web
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: web
    template:
      metadata:
        labels:
          name: web
      spec:
        containers:
          - env:
              - name: FLASK_APP
                valueFrom:
                  configMapKeyRef:
                    key: flask-app
                    name: turnpike-env
              - name: PYTHONUNBUFFERED
                value: "1"
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    key: secret-key
                    name: secret-key
              - name: SERVER_NAME
                valueFrom:
                  configMapKeyRef:
                    key: flask-server-name
                    name: turnpike-env
              - name: FLASK_ENV
                valueFrom:
                  configMapKeyRef:
                    key: flask-env
                    name: turnpike-env
              - name: REDIS_HOST
                valueFrom:
                  configMapKeyRef:
                    key: redis-service-name
                    name: turnpike-env
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: redis-password
                    name: redis-password
            image: quay.io/cloudservices/turnpike-web:${IMAGE_TAG}
            imagePullPolicy: Always
            name: web
            ports:
              - containerPort: 5000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /usr/src/app/saml/
                name: turnpike-saml
                readOnly: true
              - mountPath: /etc/turnpike
                name: turnpike-routes
                readOnly: true
            hostname: web
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        volumes:
          - name: turnpike-saml
            configMap:
              name: turnpike-saml
          - configMap:
              name: turnpike-routes
            name: turnpike-routes
parameters:
- description: Initial amount of memory the Django container will request.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the Django container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Initial amount of cpu the Django container will request.
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 200m
- description: Maximum amount of cpu the Django container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: 500m
- description: Image tag
  name: IMAGE_TAG
  required: true
